# Copyright Vespa.ai. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
# frozen_string_literal: true

source "https://rubygems.org"

# Manage our dependency on the version of the github-pages gem here.
gem 'github-pages', group: :jekyll_plugins
