---
name: Link Checker

on:
  workflow_call:
    inputs:
      ignore-urls:
        description: |
          List of Strings or RegExps to ignore URLs, one per line.
          Ref "ignore_urls" in https://github.com/gjtorikian/html-proofer?tab=readme-ov-file#configuration
        required: false
        type: string
        default: |-
          /example.com.*/
      ignore-files:
        description: |
          List of Strings or RegExps to ignore files, one per line.
          Ref "ignore_files" in https://github.com/gjtorikian/html-proofer?tab=readme-ov-file#configuration
        required: false
        type: string
        default: ""
      swap-urls:
        description: |
          List of patterns to swap URLs. The pattern is in the form of "pattern:replacement".
          Ref https://github.com/gjtorikian/html-proofer?tab=readme-ov-file#swapping-information
        required: false
        type: string
        default: |-
          (https\://github.com.*/master/.*)#.*:\1
          (https\://github.com.*/main/.*)#.*:\1
          (https\://github.com.*/blob/.*)#.*:\1
      additional-args:
        description: |
          Additional arguments to pass to htmlproofer.

          Example: "--ignore-missing-alt --ignore-status-codes '999,401,404'"
        required: false
        type: string
        default: ""
      build-plugins:
        description: |
          List of plugins to build before building the site, must be one per line.
        required: false
        type: string
        default: ""
      add-no-render-with-liquid:
        description: |
          Set to "true" to adds`render_with_liquid: false` to a set of files before building the site.

          File types: *.md, *.java, *.sd, services.xml, hosts.xml, deployment.xml
        required: false
        type: string
        default: "false"
      pre-check-script:
        description: |
          Path to the script to run before checking the links.
        required: false
        type: string
        default: ""

defaults:
  run:
    # Specify to ensure "pipefail and errexit" are set.
    # Ref: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defaultsrunshell
    shell: bash

jobs:
  htmlproofer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Do not render with liquid
        if: ${{ inputs.add-no-render-with-liquid == 'true' }}
        run: |
          find . -not -path './_site/*' \( -name '*.md' -or -name '*.java' -or -name '*.sd' \) | \
            while read f; do (echo -e "---\nrender_with_liquid: false\n---\n"; cat ${f})>${f}.new; mv ${f}.new ${f}; done
          find . -not -path './_site/*' \( -name services.xml -or -name hosts.xml -or -name deployment.xml \) | \
            while read f; do (echo -e "---\nrender_with_liquid: false\n---\n"; cat ${f})>${f}.new; mv ${f}.new ${f}; done

      - name: Build Plugins
        if: ${{ inputs.build-plugins }}
        run: |
          PLUGINS=(${{ inputs.build-plugins }})
          for plg in "${PLUGINS[@]}";
          do
            echo "Building plugin: $plg"
            bundle exec jekyll build -p "$plg"
          done

      - name: Build site
        run: |
          bundle exec jekyll build

      - name: Clean redirections
        run: |
          # Remove the redirect-files before link-check
          find _site/ -name '*.html' -print0 | \
            xargs -0 -n 100 --no-run-if-empty grep -l "Click here if you are not redirected." || true | \
            xargs --no-run-if-empty rm

      - name: Clean code elements from html
        run: |
          # htmlproofer does not check links inside "<code>" and "<pre>" elements
          find _site -name '*.html' | xargs sed -i'' 's/<code[^>]*>//g; s/<\/code>//g; s/<pre[^>]*>//g; s/<\/pre>//g;'

      - name: Run pre-check script
        if: ${{ inputs.pre-check-script }}
        run: |
          ${{ inputs.pre-check-script }}

      - name: check links without github.com
        env:
          LANG: "C.UTF-8"
        run: |
          # Merge all lines in the inputs and join them with a comma.
          IGNORE_URLS="$( echo "/github.com/ ${{ inputs.ignore-urls }}" | awk '{gsub(/ /, "", $0); print}' ORS=',' )"
          IGNORE_FILES="$( echo "${{ inputs.ignore-files }}" | awk '{gsub(/ /, "", $0); print}' ORS=',' )"
          SWAP_URLS="$( echo "${{ inputs.swap-urls }}" | awk '{gsub(/ /, "", $0); print}' ORS=',' )"

          if [[ "${{ runner.debug }}" == "1" ]]; then
            echo "IGNORE_URLS: ${IGNORE_URLS}"
            echo "IGNORE_FILES: ${IGNORE_FILES}"
            echo "SWAP_URLS: ${SWAP_URLS}"
          fi

          bundle exec htmlproofer \
            --allow-missing-href \
            --hydra '{"max_concurrency": 1}' \
            --ignore-files "${IGNORE_FILES}" \
            --ignore-urls "${IGNORE_URLS}" \
            --no-check-external-hash \
            --no-enforce-https \
            --swap-urls "${SWAP_URLS}" \
            --typhoeus '{"connecttimeout": 10, "timeout": 30, "accept_encoding": "zstd,br,gzip,deflate"}' \
            ${{ inputs.additional-args }} \
            _site

      - name: check links github.com only
        env:
          LANG: "C.UTF-8"
        run: |
          # Merge all lines in the inputs and join them with a comma.
          IGNORE_URLS='/^(?!.*github\.com).*$/'
          IGNORE_FILES="$( echo "${{ inputs.ignore-files }}" | awk '{gsub(/ /, "", $0); print}' ORS=',' )"
          SWAP_URLS="$( echo "${{ inputs.swap-urls }}" | awk '{gsub(/ /, "", $0); print}' ORS=',' )"

          if [[ "${{ runner.debug }}" == "1" ]]; then
            echo "IGNORE_URLS: ${IGNORE_URLS}"
            echo "IGNORE_FILES: ${IGNORE_FILES}"
            echo "SWAP_URLS: ${SWAP_URLS}"
          fi

          bundle exec htmlproofer \
            --allow-missing-href \
            --hydra '{"max_concurrency": 1}' \
            --ignore-files "${IGNORE_FILES}" \
            --ignore-urls "${IGNORE_URLS}" \
            --no-check-external-hash \
            --no-enforce-https \
            --swap-urls "${SWAP_URLS}" \
            --typhoeus '{"connecttimeout": 10, "timeout": 30, "accept_encoding": "zstd,br,gzip,deflate"}' \
            ${{ inputs.additional-args }} \
            _site
