---
name: Lint

on:
  push:
    branches:
      - 1.x
  pull_request:
    branches:
      - 1.x

defaults:
  run:
    # Specify to ensure "pipefail and errexit" are set.
    # Ref: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defaultsrunshell
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint YAML files
        working-directory: .github/workflows/
        run: |
          yamllint --format github .
