name: "Sync CODEOWNERS <=> OWNERS"
#
# This workflow takes the existing OWNERS files in the repository and generates a CODEOWNERS file.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
#
# Why this workflow?
# - The CODEOWNERS file is used to define the owners of the repository and the files in it.
# - The OWNERS files are used to define the owners of specific directories and files in the repository.
# - We already have OWNERS files in the repository, so we can use them to generate the CODEOWNERS file.
#

on:
  workflow_call:

defaults:
  run:
    # Specify to ensure "pipefail and errexit" are set.
    # Ref: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defaultsrunshell
    shell: bash

jobs:
  sync-codeowners:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Collect OWNERS files and generate CODEOWNERS
        run: |
          # Find all OWNERS files and generate CODEOWNERS content
          CODEOWNERS_CONTENT="# CODEOWNERS file\n# This file is automatically generated from the OWNERS files in the repository.\n# For more information, see: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners\n\n"
          for OWNERS_FILE in $(find . -name 'OWNERS'); do
            RELATIVE_PATH=$(dirname "$OWNERS_FILE")
            OWNERS=$(cat "$OWNERS_FILE" | xargs -n1 | sed 's/^/@/' | xargs)
            CODEOWNERS_CONTENT+="$RELATIVE_PATH/* $OWNERS\n"
          done

          # Save the generated CODEOWNERS content
          echo -e "$CODEOWNERS_CONTENT" > .github/CODEOWNERS.generated

      - name: Check if CODEOWNERS file needs update
        id: check_diff
        run: |
          if ! cmp -s .github/CODEOWNERS .github/CODEOWNERS.generated; then
            echo "needs_update=true" >> $GITHUB_OUTPUT
          else
            echo "needs_update=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit updated CODEOWNERS
        if: steps.check_diff.outputs.needs_update == 'true'
        run: |
          mv .github/CODEOWNERS.generated .github/CODEOWNERS
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/CODEOWNERS
          git commit -m "Update CODEOWNERS file"
          git push origin HEAD:${GITHUB_REF}
